# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.8
    environment: # environment variables for cloudamqp
      AMQP_URL: amqp://kydmeghh:iHkk6RrbPHnkUhkyuBd8ULnGhlQ6EbjB@toad.rmq.cloudamqp.com/kydmeghh

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to es-consumer
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$ES_CONSUMER.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
